name: Release WordPress Plugin

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create release archive
        run: |
          mkdir release
          rsync -av --exclude={'.git','.github','.gitignore','tests','*.json','*.xml'} ./ release/
          cd release && zip -r ../plugin-release.zip .

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./plugin-release.zip
          asset_name: plugin-release.zip
          asset_content_type: application/zip
